/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VotingPowerRouteImport } from './routes/voting-power'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProposalsIdRouteImport } from './routes/proposals.$id'
import { Route as CommentsIdRouteImport } from './routes/comments.$id'

const VotingPowerRoute = VotingPowerRouteImport.update({
  id: '/voting-power',
  path: '/voting-power',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsIdRoute = ProposalsIdRouteImport.update({
  id: '/proposals/$id',
  path: '/proposals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsIdRoute = CommentsIdRouteImport.update({
  id: '/comments/$id',
  path: '/comments/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/voting-power': typeof VotingPowerRoute
  '/comments/$id': typeof CommentsIdRoute
  '/proposals/$id': typeof ProposalsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/voting-power': typeof VotingPowerRoute
  '/comments/$id': typeof CommentsIdRoute
  '/proposals/$id': typeof ProposalsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/voting-power': typeof VotingPowerRoute
  '/comments/$id': typeof CommentsIdRoute
  '/proposals/$id': typeof ProposalsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/voting-power' | '/comments/$id' | '/proposals/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/voting-power' | '/comments/$id' | '/proposals/$id'
  id: '__root__' | '/' | '/voting-power' | '/comments/$id' | '/proposals/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VotingPowerRoute: typeof VotingPowerRoute
  CommentsIdRoute: typeof CommentsIdRoute
  ProposalsIdRoute: typeof ProposalsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voting-power': {
      id: '/voting-power'
      path: '/voting-power'
      fullPath: '/voting-power'
      preLoaderRoute: typeof VotingPowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals/$id': {
      id: '/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/proposals/$id'
      preLoaderRoute: typeof ProposalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments/$id': {
      id: '/comments/$id'
      path: '/comments/$id'
      fullPath: '/comments/$id'
      preLoaderRoute: typeof CommentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VotingPowerRoute: VotingPowerRoute,
  CommentsIdRoute: CommentsIdRoute,
  ProposalsIdRoute: ProposalsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
