/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TimeRouteImport } from './routes/time'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SaturationRouteImport } from './routes/saturation'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RecruitingRouteImport } from './routes/recruiting'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as OrgRouteImport } from './routes/org'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OfficesRouteImport } from './routes/offices'
import { Route as MomentsRouteImport } from './routes/moments'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogRouteImport } from './routes/log'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as KudosRouteImport } from './routes/kudos'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as LogIndexRouteImport } from './routes/log.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ProposalIdRouteImport } from './routes/proposal.$id'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as PeopleEmployeeIdRouteImport } from './routes/people_.$employeeId'
import { Route as OfficesOfficeIdRouteImport } from './routes/offices.$officeId'
import { Route as LogRecapRouteImport } from './routes/log.recap'
import { Route as LogEmployeeIdRouteImport } from './routes/log.$employeeId'
import { Route as DocsSaturationRouteImport } from './routes/docs.saturation'
import { Route as DocsKudosRouteImport } from './routes/docs.kudos'
import { Route as DocsIntegrationsRouteImport } from './routes/docs.integrations'
import { Route as DocsEmployeeScoreRouteImport } from './routes/docs.employee-score'
import { Route as DocsClientsProjectsRouteImport } from './routes/docs.clients-projects'
import { Route as CommentIdRouteImport } from './routes/comment.$id'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as AdminModulesRouteImport } from './routes/admin.modules'
import { Route as OfficesOfficeIdRoomIdRouteImport } from './routes/offices.$officeId.$roomId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeRoute = TimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SaturationRoute = SaturationRouteImport.update({
  id: '/saturation',
  path: '/saturation',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitingRoute = RecruitingRouteImport.update({
  id: '/recruiting',
  path: '/recruiting',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficesRoute = OfficesRouteImport.update({
  id: '/offices',
  path: '/offices',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentsRoute = MomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const KudosRoute = KudosRouteImport.update({
  id: '/kudos',
  path: '/kudos',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogIndexRoute = LogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LogRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientsRoute,
} as any)
const ProposalIdRoute = ProposalIdRouteImport.update({
  id: '/proposal/$id',
  path: '/proposal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleEmployeeIdRoute = PeopleEmployeeIdRouteImport.update({
  id: '/people_/$employeeId',
  path: '/people/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficesOfficeIdRoute = OfficesOfficeIdRouteImport.update({
  id: '/$officeId',
  path: '/$officeId',
  getParentRoute: () => OfficesRoute,
} as any)
const LogRecapRoute = LogRecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => LogRoute,
} as any)
const LogEmployeeIdRoute = LogEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => LogRoute,
} as any)
const DocsSaturationRoute = DocsSaturationRouteImport.update({
  id: '/saturation',
  path: '/saturation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsKudosRoute = DocsKudosRouteImport.update({
  id: '/kudos',
  path: '/kudos',
  getParentRoute: () => DocsRoute,
} as any)
const DocsIntegrationsRoute = DocsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DocsRoute,
} as any)
const DocsEmployeeScoreRoute = DocsEmployeeScoreRouteImport.update({
  id: '/employee-score',
  path: '/employee-score',
  getParentRoute: () => DocsRoute,
} as any)
const DocsClientsProjectsRoute = DocsClientsProjectsRouteImport.update({
  id: '/clients-projects',
  path: '/clients-projects',
  getParentRoute: () => DocsRoute,
} as any)
const CommentIdRoute = CommentIdRouteImport.update({
  id: '/comment/$id',
  path: '/comment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/admin/modules',
  path: '/admin/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficesOfficeIdRoomIdRoute = OfficesOfficeIdRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => OfficesOfficeIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/announcements': typeof AnnouncementsRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/expenses': typeof ExpensesRoute
  '/feedback': typeof FeedbackRoute
  '/focus': typeof FocusRoute
  '/forecast': typeof ForecastRoute
  '/growth': typeof GrowthRoute
  '/kudos': typeof KudosRoute
  '/leave': typeof LeaveRoute
  '/log': typeof LogRouteWithChildren
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/moments': typeof MomentsRoute
  '/offices': typeof OfficesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/org': typeof OrgRoute
  '/payroll': typeof PayrollRoute
  '/people': typeof PeopleRoute
  '/profile': typeof ProfileRoute
  '/recruiting': typeof RecruitingRoute
  '/reports': typeof ReportsRoute
  '/saturation': typeof SaturationRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/time': typeof TimeRoute
  '/welcome': typeof WelcomeRoute
  '/admin/modules': typeof AdminModulesRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/comment/$id': typeof CommentIdRoute
  '/docs/clients-projects': typeof DocsClientsProjectsRoute
  '/docs/employee-score': typeof DocsEmployeeScoreRoute
  '/docs/integrations': typeof DocsIntegrationsRoute
  '/docs/kudos': typeof DocsKudosRoute
  '/docs/saturation': typeof DocsSaturationRoute
  '/log/$employeeId': typeof LogEmployeeIdRoute
  '/log/recap': typeof LogRecapRoute
  '/offices/$officeId': typeof OfficesOfficeIdRouteWithChildren
  '/people/$employeeId': typeof PeopleEmployeeIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/proposal/$id': typeof ProposalIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/log/': typeof LogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/offices/$officeId/$roomId': typeof OfficesOfficeIdRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/announcements': typeof AnnouncementsRoute
  '/calendar': typeof CalendarRoute
  '/developers': typeof DevelopersRoute
  '/documents': typeof DocumentsRoute
  '/expenses': typeof ExpensesRoute
  '/feedback': typeof FeedbackRoute
  '/focus': typeof FocusRoute
  '/forecast': typeof ForecastRoute
  '/growth': typeof GrowthRoute
  '/kudos': typeof KudosRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/moments': typeof MomentsRoute
  '/offices': typeof OfficesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/org': typeof OrgRoute
  '/payroll': typeof PayrollRoute
  '/people': typeof PeopleRoute
  '/profile': typeof ProfileRoute
  '/recruiting': typeof RecruitingRoute
  '/reports': typeof ReportsRoute
  '/saturation': typeof SaturationRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/time': typeof TimeRoute
  '/welcome': typeof WelcomeRoute
  '/admin/modules': typeof AdminModulesRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/comment/$id': typeof CommentIdRoute
  '/docs/clients-projects': typeof DocsClientsProjectsRoute
  '/docs/employee-score': typeof DocsEmployeeScoreRoute
  '/docs/integrations': typeof DocsIntegrationsRoute
  '/docs/kudos': typeof DocsKudosRoute
  '/docs/saturation': typeof DocsSaturationRoute
  '/log/$employeeId': typeof LogEmployeeIdRoute
  '/log/recap': typeof LogRecapRoute
  '/offices/$officeId': typeof OfficesOfficeIdRouteWithChildren
  '/people/$employeeId': typeof PeopleEmployeeIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/proposal/$id': typeof ProposalIdRoute
  '/clients': typeof ClientsIndexRoute
  '/docs': typeof DocsIndexRoute
  '/log': typeof LogIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/offices/$officeId/$roomId': typeof OfficesOfficeIdRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/announcements': typeof AnnouncementsRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/expenses': typeof ExpensesRoute
  '/feedback': typeof FeedbackRoute
  '/focus': typeof FocusRoute
  '/forecast': typeof ForecastRoute
  '/growth': typeof GrowthRoute
  '/kudos': typeof KudosRoute
  '/leave': typeof LeaveRoute
  '/log': typeof LogRouteWithChildren
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/moments': typeof MomentsRoute
  '/offices': typeof OfficesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/org': typeof OrgRoute
  '/payroll': typeof PayrollRoute
  '/people': typeof PeopleRoute
  '/profile': typeof ProfileRoute
  '/recruiting': typeof RecruitingRoute
  '/reports': typeof ReportsRoute
  '/saturation': typeof SaturationRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/time': typeof TimeRoute
  '/welcome': typeof WelcomeRoute
  '/admin/modules': typeof AdminModulesRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/comment/$id': typeof CommentIdRoute
  '/docs/clients-projects': typeof DocsClientsProjectsRoute
  '/docs/employee-score': typeof DocsEmployeeScoreRoute
  '/docs/integrations': typeof DocsIntegrationsRoute
  '/docs/kudos': typeof DocsKudosRoute
  '/docs/saturation': typeof DocsSaturationRoute
  '/log/$employeeId': typeof LogEmployeeIdRoute
  '/log/recap': typeof LogRecapRoute
  '/offices/$officeId': typeof OfficesOfficeIdRouteWithChildren
  '/people_/$employeeId': typeof PeopleEmployeeIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/proposal/$id': typeof ProposalIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/log/': typeof LogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/offices/$officeId/$roomId': typeof OfficesOfficeIdRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/announcements'
    | '/calendar'
    | '/clients'
    | '/developers'
    | '/docs'
    | '/documents'
    | '/expenses'
    | '/feedback'
    | '/focus'
    | '/forecast'
    | '/growth'
    | '/kudos'
    | '/leave'
    | '/log'
    | '/login'
    | '/marketplace'
    | '/moments'
    | '/offices'
    | '/onboarding'
    | '/org'
    | '/payroll'
    | '/people'
    | '/profile'
    | '/recruiting'
    | '/reports'
    | '/saturation'
    | '/settings'
    | '/signup'
    | '/time'
    | '/welcome'
    | '/admin/modules'
    | '/clients/$clientId'
    | '/comment/$id'
    | '/docs/clients-projects'
    | '/docs/employee-score'
    | '/docs/integrations'
    | '/docs/kudos'
    | '/docs/saturation'
    | '/log/$employeeId'
    | '/log/recap'
    | '/offices/$officeId'
    | '/people/$employeeId'
    | '/projects/$projectId'
    | '/proposal/$id'
    | '/clients/'
    | '/docs/'
    | '/log/'
    | '/projects/'
    | '/offices/$officeId/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/announcements'
    | '/calendar'
    | '/developers'
    | '/documents'
    | '/expenses'
    | '/feedback'
    | '/focus'
    | '/forecast'
    | '/growth'
    | '/kudos'
    | '/leave'
    | '/login'
    | '/marketplace'
    | '/moments'
    | '/offices'
    | '/onboarding'
    | '/org'
    | '/payroll'
    | '/people'
    | '/profile'
    | '/recruiting'
    | '/reports'
    | '/saturation'
    | '/settings'
    | '/signup'
    | '/time'
    | '/welcome'
    | '/admin/modules'
    | '/clients/$clientId'
    | '/comment/$id'
    | '/docs/clients-projects'
    | '/docs/employee-score'
    | '/docs/integrations'
    | '/docs/kudos'
    | '/docs/saturation'
    | '/log/$employeeId'
    | '/log/recap'
    | '/offices/$officeId'
    | '/people/$employeeId'
    | '/projects/$projectId'
    | '/proposal/$id'
    | '/clients'
    | '/docs'
    | '/log'
    | '/projects'
    | '/offices/$officeId/$roomId'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/announcements'
    | '/calendar'
    | '/clients'
    | '/developers'
    | '/docs'
    | '/documents'
    | '/expenses'
    | '/feedback'
    | '/focus'
    | '/forecast'
    | '/growth'
    | '/kudos'
    | '/leave'
    | '/log'
    | '/login'
    | '/marketplace'
    | '/moments'
    | '/offices'
    | '/onboarding'
    | '/org'
    | '/payroll'
    | '/people'
    | '/profile'
    | '/recruiting'
    | '/reports'
    | '/saturation'
    | '/settings'
    | '/signup'
    | '/time'
    | '/welcome'
    | '/admin/modules'
    | '/clients/$clientId'
    | '/comment/$id'
    | '/docs/clients-projects'
    | '/docs/employee-score'
    | '/docs/integrations'
    | '/docs/kudos'
    | '/docs/saturation'
    | '/log/$employeeId'
    | '/log/recap'
    | '/offices/$officeId'
    | '/people_/$employeeId'
    | '/projects/$projectId'
    | '/proposal/$id'
    | '/clients/'
    | '/docs/'
    | '/log/'
    | '/projects/'
    | '/offices/$officeId/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  CalendarRoute: typeof CalendarRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  DevelopersRoute: typeof DevelopersRoute
  DocsRoute: typeof DocsRouteWithChildren
  DocumentsRoute: typeof DocumentsRoute
  ExpensesRoute: typeof ExpensesRoute
  FeedbackRoute: typeof FeedbackRoute
  FocusRoute: typeof FocusRoute
  ForecastRoute: typeof ForecastRoute
  GrowthRoute: typeof GrowthRoute
  KudosRoute: typeof KudosRoute
  LeaveRoute: typeof LeaveRoute
  LogRoute: typeof LogRouteWithChildren
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MomentsRoute: typeof MomentsRoute
  OfficesRoute: typeof OfficesRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  OrgRoute: typeof OrgRoute
  PayrollRoute: typeof PayrollRoute
  PeopleRoute: typeof PeopleRoute
  ProfileRoute: typeof ProfileRoute
  RecruitingRoute: typeof RecruitingRoute
  ReportsRoute: typeof ReportsRoute
  SaturationRoute: typeof SaturationRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TimeRoute: typeof TimeRoute
  WelcomeRoute: typeof WelcomeRoute
  AdminModulesRoute: typeof AdminModulesRoute
  CommentIdRoute: typeof CommentIdRoute
  PeopleEmployeeIdRoute: typeof PeopleEmployeeIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProposalIdRoute: typeof ProposalIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time': {
      id: '/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof TimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saturation': {
      id: '/saturation'
      path: '/saturation'
      fullPath: '/saturation'
      preLoaderRoute: typeof SaturationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiting': {
      id: '/recruiting'
      path: '/recruiting'
      fullPath: '/recruiting'
      preLoaderRoute: typeof RecruitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offices': {
      id: '/offices'
      path: '/offices'
      fullPath: '/offices'
      preLoaderRoute: typeof OfficesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments': {
      id: '/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof MomentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kudos': {
      id: '/kudos'
      path: '/kudos'
      fullPath: '/kudos'
      preLoaderRoute: typeof KudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log/': {
      id: '/log/'
      path: '/'
      fullPath: '/log/'
      preLoaderRoute: typeof LogIndexRouteImport
      parentRoute: typeof LogRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/clients/': {
      id: '/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/proposal/$id': {
      id: '/proposal/$id'
      path: '/proposal/$id'
      fullPath: '/proposal/$id'
      preLoaderRoute: typeof ProposalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people_/$employeeId': {
      id: '/people_/$employeeId'
      path: '/people/$employeeId'
      fullPath: '/people/$employeeId'
      preLoaderRoute: typeof PeopleEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offices/$officeId': {
      id: '/offices/$officeId'
      path: '/$officeId'
      fullPath: '/offices/$officeId'
      preLoaderRoute: typeof OfficesOfficeIdRouteImport
      parentRoute: typeof OfficesRoute
    }
    '/log/recap': {
      id: '/log/recap'
      path: '/recap'
      fullPath: '/log/recap'
      preLoaderRoute: typeof LogRecapRouteImport
      parentRoute: typeof LogRoute
    }
    '/log/$employeeId': {
      id: '/log/$employeeId'
      path: '/$employeeId'
      fullPath: '/log/$employeeId'
      preLoaderRoute: typeof LogEmployeeIdRouteImport
      parentRoute: typeof LogRoute
    }
    '/docs/saturation': {
      id: '/docs/saturation'
      path: '/saturation'
      fullPath: '/docs/saturation'
      preLoaderRoute: typeof DocsSaturationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/kudos': {
      id: '/docs/kudos'
      path: '/kudos'
      fullPath: '/docs/kudos'
      preLoaderRoute: typeof DocsKudosRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/integrations': {
      id: '/docs/integrations'
      path: '/integrations'
      fullPath: '/docs/integrations'
      preLoaderRoute: typeof DocsIntegrationsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/employee-score': {
      id: '/docs/employee-score'
      path: '/employee-score'
      fullPath: '/docs/employee-score'
      preLoaderRoute: typeof DocsEmployeeScoreRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/clients-projects': {
      id: '/docs/clients-projects'
      path: '/clients-projects'
      fullPath: '/docs/clients-projects'
      preLoaderRoute: typeof DocsClientsProjectsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/comment/$id': {
      id: '/comment/$id'
      path: '/comment/$id'
      fullPath: '/comment/$id'
      preLoaderRoute: typeof CommentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/admin/modules': {
      id: '/admin/modules'
      path: '/admin/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offices/$officeId/$roomId': {
      id: '/offices/$officeId/$roomId'
      path: '/$roomId'
      fullPath: '/offices/$officeId/$roomId'
      preLoaderRoute: typeof OfficesOfficeIdRoomIdRouteImport
      parentRoute: typeof OfficesOfficeIdRoute
    }
  }
}

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface DocsRouteChildren {
  DocsClientsProjectsRoute: typeof DocsClientsProjectsRoute
  DocsEmployeeScoreRoute: typeof DocsEmployeeScoreRoute
  DocsIntegrationsRoute: typeof DocsIntegrationsRoute
  DocsKudosRoute: typeof DocsKudosRoute
  DocsSaturationRoute: typeof DocsSaturationRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsClientsProjectsRoute: DocsClientsProjectsRoute,
  DocsEmployeeScoreRoute: DocsEmployeeScoreRoute,
  DocsIntegrationsRoute: DocsIntegrationsRoute,
  DocsKudosRoute: DocsKudosRoute,
  DocsSaturationRoute: DocsSaturationRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface LogRouteChildren {
  LogEmployeeIdRoute: typeof LogEmployeeIdRoute
  LogRecapRoute: typeof LogRecapRoute
  LogIndexRoute: typeof LogIndexRoute
}

const LogRouteChildren: LogRouteChildren = {
  LogEmployeeIdRoute: LogEmployeeIdRoute,
  LogRecapRoute: LogRecapRoute,
  LogIndexRoute: LogIndexRoute,
}

const LogRouteWithChildren = LogRoute._addFileChildren(LogRouteChildren)

interface OfficesOfficeIdRouteChildren {
  OfficesOfficeIdRoomIdRoute: typeof OfficesOfficeIdRoomIdRoute
}

const OfficesOfficeIdRouteChildren: OfficesOfficeIdRouteChildren = {
  OfficesOfficeIdRoomIdRoute: OfficesOfficeIdRoomIdRoute,
}

const OfficesOfficeIdRouteWithChildren = OfficesOfficeIdRoute._addFileChildren(
  OfficesOfficeIdRouteChildren,
)

interface OfficesRouteChildren {
  OfficesOfficeIdRoute: typeof OfficesOfficeIdRouteWithChildren
}

const OfficesRouteChildren: OfficesRouteChildren = {
  OfficesOfficeIdRoute: OfficesOfficeIdRouteWithChildren,
}

const OfficesRouteWithChildren =
  OfficesRoute._addFileChildren(OfficesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  CalendarRoute: CalendarRoute,
  ClientsRoute: ClientsRouteWithChildren,
  DevelopersRoute: DevelopersRoute,
  DocsRoute: DocsRouteWithChildren,
  DocumentsRoute: DocumentsRoute,
  ExpensesRoute: ExpensesRoute,
  FeedbackRoute: FeedbackRoute,
  FocusRoute: FocusRoute,
  ForecastRoute: ForecastRoute,
  GrowthRoute: GrowthRoute,
  KudosRoute: KudosRoute,
  LeaveRoute: LeaveRoute,
  LogRoute: LogRouteWithChildren,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  MomentsRoute: MomentsRoute,
  OfficesRoute: OfficesRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  OrgRoute: OrgRoute,
  PayrollRoute: PayrollRoute,
  PeopleRoute: PeopleRoute,
  ProfileRoute: ProfileRoute,
  RecruitingRoute: RecruitingRoute,
  ReportsRoute: ReportsRoute,
  SaturationRoute: SaturationRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TimeRoute: TimeRoute,
  WelcomeRoute: WelcomeRoute,
  AdminModulesRoute: AdminModulesRoute,
  CommentIdRoute: CommentIdRoute,
  PeopleEmployeeIdRoute: PeopleEmployeeIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProposalIdRoute: ProposalIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
